[package]
name = "r-2023-04-20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="*"
hyper={ version = "0.14", features = ["full"] }
hyper-tls="*"
tokio={ version = "1", features = ["full"] }
